Add methods about the MTCS commands
lsst-ts/LOVE-commander pull request #41
Opened 2021-12-10 20:08 UTC by fdelcampo

Add methods:
- connect_to_mtcs_intance
- maintel_command
- maintel_docstrings
- unavailable_mtcs_client

Change URL for the docstrings:
- /aux/docstrings
- /main/docstrings

2021-12-10 20:33 UTC, sebastian-aranda requested changes
It looks good, but I'm missing the tests. Once you have that ready I can approve the PR.

2021-12-10 20:33 UTC, sebastian-aranda commented on commander/tcs.py
> +# import lsst.ts.observatory.control.auxtel as auxtel
This line should be removed

2021-12-10 20:33 UTC, sebastian-aranda commented on commander/tcs.py
> +    def unavailable_mtcs_client():
I would move this method between `connect_to_mtcs_intance` and `maintel_command`, near line 88

2022-03-02 18:52 UTC, areyesd14 approved these changes
Looks good. Thanks!

2022-03-02 19:06 UTC, merged